// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: nfsygxjatvckiqbtjink

class SupabaseConfig {
  static const String supabaseUrl = 'https://nfsygxjatvckiqbtjink.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mc3lneGphdHZja2lxYnRqaW5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQyMDkyOTIsImV4cCI6MjA3OTc4NTI5Mn0.IQnPAvL4_fn08OeBbYziLLeF5zYxLI7Tyf-9AGU84Hk';
}
